### ISSUE TITLE
Failed to build tauri app on win10

### ISSUE THREAD

**Issue by testforvln** [jetli/rust-yew-axum-tauri-desktop#1] opened 2022-05-14 13:03 UTC
Hi, I followed the instructions and successed getting the template app run with "cargo tauri dev". 

But when I run "cargo tauri build", the generated app.exe failed to show anything with only blank window.

**Comment by bobbbay** [comment] 2022-07-18 23:27
Looking at the source code, this seems to be the intended behaviour.

**Comment by novvoo** [comment] 2022-07-22 06:47
http://127.0.0.1:8080  --->   https://tauri.localhost/
![4247.png](http://tva1.sinaimg.cn/large/6e557adagy1h4fpbxiye9j218k0hjacb.jpg)

**Comment by testforvln** [comment] 2022-08-13 09:15
Thx @jingslunt !

**Comment by jetli** [comment] 2022-10-25 08:30
should be fixed

**Closed as completed by jetli** 2022-10-25 08:30 UTC
